version: '3.7'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: redis:5-alpine
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis/data/:/data/
